### ISSUE TITLE
tensorflowsharp

### ISSUE THREAD

**Issue by halukmy** [DotNetToscana/CustomVisionCompanion#1]
looks better than jar i guess

**Comment by marcominerva** [comment]
Hi! Could you please explain better what do you mean?

**Comment by marcominerva** [comment]
Close as inactive. @halukmy, if you need something else feel free to ask again.

**Comment by halukmy** [comment]
thanks so much @marcominerva 

i just try to say, i want to learn deep learning and working with ai,

so there is a tool with Tensorflowsharp made by google and codded for .net

so im so happy if you can make me learn about it
